version: '3'

services:
  web:
    build: .
    restart: always
    networks:
      - web-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.abdos-site.rule=Host(`abdos.cloud`) || Host(`www.abdos.cloud`)"
      - "traefik.http.routers.abdos-site.entrypoints=https"
      - "traefik.http.routers.abdos-site.tls=true"
      - "traefik.http.routers.abdos-site.tls.certresolver=simple-resolver"
      - "traefik.http.services.abdos-site.loadbalancer.server.port=80"

networks:
  web-network:
    external: true